/**
 * townSpotlight.ts
 * Unique "Local Industry Spotlight" paragraphs for the top ~80 highest-traffic
 * service-area towns. Each entry references specific local industrial estates,
 * business parks, employers, or infrastructure to differentiate the page content
 * for Google's quality threshold.
 *
 * For towns NOT in this map, generateTownSpotlight() falls back to a
 * county-context-aware template paragraph.
 */

export const townSpotlight: Record<string, string> = {
  // ── West Midlands ──────────────────────────────────────────────────────────
  "birmingham": "Birmingham's manufacturing corridor — stretching from Tyseley Industrial Estate through Aston and Smethwick — generates significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's ongoing HS2 construction programme and major commercial regeneration projects across Digbeth and the Jewellery Quarter provide consistent work for mobile shot blasting contractors serving the West Midlands.",
  "coventry": "Coventry's automotive and aerospace supply chain — anchored by the Manufacturing Technology Centre (MTC) at Ansty Park and major employers along the A45 industrial corridor — creates steady demand for precision surface preparation on structural steel, tooling, and specialist equipment. The city's ambitious regeneration of the city centre and Friargate business district also drives demand for commercial shot blasting services.",
  "wolverhampton": "Wolverhampton's industrial heritage is reflected in its active manufacturing base at i54 South Staffordshire and Pensnett Trading Estate, where engineering, automotive components, and fabrication businesses regularly require shot blasting and protective coating services. The city's ongoing commercial construction activity around the Waterfront and Stafford Road corridor provides additional demand for structural steelwork preparation.",
  "walsall": "Walsall's leather goods, metal finishing, and light engineering industries — concentrated around Darlaston and Bloxwich — generate consistent demand for shot blasting services on plant, machinery, and fabricated metalwork. The Birchley Island industrial area and Aldridge Business Park host a range of manufacturing businesses requiring regular surface preparation and protective coating maintenance.",
  "dudley": "Dudley's Black Country manufacturing heritage continues through active industrial estates at Pensnett, Brierley Hill, and Round Oak, where steel fabricators, engineering firms, and construction contractors regularly require shot blasting services. The Merry Hill commercial development and ongoing regeneration of the town centre also generate demand for structural steel and cladding restoration work.",

  // ── West Yorkshire ─────────────────────────────────────────────────────────
  "leeds": "Leeds is one of the UK's fastest-growing commercial construction markets, with major steel-framed developments across the South Bank, Wellington Place, and the wider city region generating consistent demand for structural steel shot blasting and surface preparation. The city's strong engineering, food processing, and logistics sectors — centred around Stourton, Hunslet, and Morley — also produce significant volumes of plant and machinery requiring specialist surface treatment.",
  "bradford": "Bradford's textile, engineering, and food manufacturing industries — concentrated in the Eureka Business Park, Bowling Back Lane industrial area, and Thornton Road corridor — generate steady demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The city's ongoing commercial regeneration and Bradford City Centre Masterplan projects provide additional demand for mobile shot blasting services.",
  "huddersfield": "Huddersfield's engineering and manufacturing base — including the Kirklees Light Railway, Crosland Moor industrial area, and the Penistone Road corridor — creates consistent demand for shot blasting services on structural steel, plant, and specialist fabrications. The town's proximity to the M62 and its role as a hub for West Yorkshire's manufacturing supply chain make it a key location for mobile shot blasting contractors.",
  "wakefield": "Wakefield's logistics, distribution, and manufacturing sectors — anchored by Normanton Industrial Estate, Calder Park, and the Wakefield Europort — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and ongoing regeneration of the Waterfront area provide additional work for mobile shot blasting services.",
  "halifax": "Halifax's engineering and manufacturing heritage — reflected in the Dean Clough industrial complex, Brighouse industrial area, and the Calder Valley manufacturing corridor — creates consistent demand for shot blasting services on structural steel, plant and machinery, and factory cladding. The town's active commercial property market and proximity to the M62 make it a key service location for West Yorkshire.",

  // ── South Yorkshire ────────────────────────────────────────────────────────
  "sheffield": "Sheffield's steel and advanced manufacturing heritage continues through active industrial clusters at Tinsley, Attercliffe, and the Advanced Manufacturing Park (AMP) at Waverley, where engineering firms, fabricators, and aerospace suppliers regularly require shot blasting and surface preparation services. The city's major commercial regeneration projects — including Heart of the City II and the Kelham Island district — also generate demand for structural steel and cladding restoration.",
  "rotherham": "Rotherham's steel fabrication, automotive, and logistics industries — concentrated at Templeborough, Parkgate, and the Advanced Manufacturing Park — generate significant demand for structural steel shot blasting, container preparation, and plant and machinery surface treatment. The town's proximity to the M1 and its role in South Yorkshire's manufacturing supply chain make it a key location for commercial shot blasting services.",
  "doncaster": "Doncaster's logistics, distribution, and manufacturing sectors — anchored by Doncaster Sheffield Airport Business Park, Balby Carr, and the iPort logistics hub — create consistent demand for structural steel shot blasting, warehouse racking preparation, and commercial vehicle surface treatment. The town's active construction market and ongoing regeneration of the city centre provide additional demand for mobile shot blasting services.",
  "barnsley": "Barnsley's manufacturing and engineering base — including the Dodworth Business Park, Wilthorpe industrial area, and the Dearne Valley Enterprise Zone — generates steady demand for shot blasting services on structural steel, plant and machinery, and factory cladding. The town's active commercial construction market and proximity to the M1 make it a key service location for South Yorkshire.",

  // ── Greater Manchester ─────────────────────────────────────────────────────
  "manchester": "Manchester's commercial construction boom — spanning Spinningfields, NOMA, and the wider city region — generates consistent demand for structural steel shot blasting and surface preparation. The city's strong engineering, food processing, and logistics sectors — centred around Trafford Park, Openshaw, and the Salford Quays — also produce significant volumes of plant and machinery requiring specialist surface treatment.",
  "salford": "Salford's MediaCityUK development and ongoing commercial regeneration of the Quays and Chapel Street corridor generate demand for structural steel shot blasting and cladding restoration. The city's traditional manufacturing base at Trafford Park — one of the UK's largest industrial estates — provides consistent work for mobile shot blasting contractors serving the Greater Manchester area.",
  "bolton": "Bolton's engineering, textiles, and food manufacturing industries — concentrated at Middlebrook Business Park, Lostock Industrial Estate, and the Chorley New Road corridor — generate steady demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The town's active commercial construction market and proximity to the M61 make it a key service location for Greater Manchester.",
  "oldham": "Oldham's manufacturing and engineering base — including the Chadderton industrial area, Hollinwood Business Centre, and the Broadway Business Park — creates consistent demand for shot blasting services on structural steel, plant and machinery, and factory cladding. The town's active commercial property market and proximity to the M60 orbital motorway make it a key location for mobile shot blasting services.",
  "rochdale": "Rochdale's engineering, textiles, and logistics industries — concentrated at Kingsway Business Park, Stakehill Industrial Estate, and the Heywood Distribution Park — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M62 provide additional demand for mobile shot blasting services.",

  // ── Merseyside ─────────────────────────────────────────────────────────────
  "liverpool": "Liverpool's port, logistics, and construction sectors — anchored by the Royal Seaforth Dock, Mersey Docks, and the Knowledge Quarter regeneration zone — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The city's active commercial construction market across Liverpool Waters and the Ten Streets district provides consistent work for mobile shot blasting contractors.",
  "birkenhead": "Birkenhead's shipbuilding heritage and active manufacturing base at Cammell Laird, Wirral International Business Park, and the Bidston industrial area generate consistent demand for structural steel shot blasting, marine surface preparation, and plant and machinery treatment. The town's proximity to the Mersey and its role in the North West's manufacturing supply chain make it a key location for commercial shot blasting services.",
  "st-helens": "St Helens' glass manufacturing, chemicals, and logistics industries — anchored by Pilkington's operations, Haydock Industrial Estate, and the Omega Business Park — generate steady demand for plant and machinery shot blasting, factory cladding restoration, and structural steelwork preparation. The town's active commercial construction market and proximity to the M6 and M62 make it a key service location for Merseyside.",

  // ── Lancashire ─────────────────────────────────────────────────────────────
  "blackburn": "Blackburn's engineering, textiles, and food manufacturing industries — concentrated at Shadsworth Business Park, Whitebirk Industrial Estate, and the Greenbank Technology Park — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The town's active commercial construction market and proximity to the M65 make it a key service location for Lancashire.",
  "burnley": "Burnley's aerospace, engineering, and manufacturing industries — anchored by the Burnley Bridge Business Park, Shuttleworth Mead Business Park, and the Heasandford Industrial Estate — create significant demand for precision surface preparation on structural steel, specialist fabrications, and plant and machinery. The town's role in the Lancashire aerospace supply chain makes it a key location for commercial shot blasting services.",
  "preston": "Preston's manufacturing, logistics, and construction sectors — concentrated at Walton Summit Industrial Estate, Cuerden Valley Business Park, and the Strand Road corridor — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the M6 and M65 provide additional demand for mobile shot blasting services.",

  // ── Cheshire ───────────────────────────────────────────────────────────────
  "chester": "Chester's construction, logistics, and food processing industries — anchored by Sealand Industrial Estate, Bumpers Lane industrial area, and the Wrexham Technology Park just across the border — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial property market and proximity to the A55 and M53 make it a key service location for Cheshire.",
  "warrington": "Warrington's logistics, chemicals, and manufacturing industries — concentrated at Birchwood Park, Gemini Retail Park, and the Woolston industrial area — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's position at the junction of the M6 and M62 makes it a central hub for commercial shot blasting services across the North West.",
  "crewe": "Crewe's railway engineering, automotive, and logistics industries — anchored by Bentley Motors' manufacturing plant, the Crewe Business Park, and the South Cheshire Growth Village — generate consistent demand for precision surface preparation on structural steel, specialist fabrications, and plant and machinery. The town's active commercial construction market and proximity to the M6 make it a key service location for Cheshire.",

  // ── East Midlands ──────────────────────────────────────────────────────────
  "nottingham": "Nottingham's pharmaceutical, engineering, and logistics industries — concentrated at Nottingham Business Park, Colwick Industrial Estate, and the Beeston industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market across the Waterside regeneration zone and Southside district provides additional demand for mobile shot blasting services.",
  "derby": "Derby's aerospace, rail engineering, and manufacturing industries — anchored by Rolls-Royce's manufacturing campus, Toyota's Burnaston plant, and the Raynesway industrial area — generate significant demand for precision surface preparation on structural steel, specialist fabrications, and plant and machinery. The city's active commercial construction market and proximity to the A38 and M1 make it a key service location for Derbyshire.",
  "leicester": "Leicester's textiles, food processing, and logistics industries — concentrated at Meridian Business Park, Optimus Point, and the Aylestone Road industrial corridor — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The city's active commercial construction market and proximity to the M1 and M69 provide additional demand for mobile shot blasting services.",
  "northampton": "Northampton's logistics, footwear manufacturing, and construction industries — anchored by Brackmills Industrial Estate, Swan Valley, and the Northampton Gateway rail freight terminal — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M1 make it a key service location for Northamptonshire.",
  "lincoln": "Lincoln's engineering, food processing, and agricultural machinery industries — concentrated at Whisby Road industrial area, Outer Circle Road, and the Tritton Road commercial corridor — generate consistent demand for plant and machinery shot blasting, structural steelwork preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the A46 provide additional demand for mobile shot blasting services.",

  // ── East of England ────────────────────────────────────────────────────────
  "cambridge": "Cambridge's technology, biomedical, and construction sectors — anchored by the Cambridge Science Park, Granta Park, and the ongoing Cambridge Biomedical Campus expansion — generate consistent demand for structural steel shot blasting and surface preparation. The city's active commercial construction market and the wider Cambridgeshire growth corridor provide significant demand for mobile shot blasting services.",
  "peterborough": "Peterborough's logistics, food processing, and construction industries — concentrated at Queensgate Business Park, Orton Southgate, and the Fengate industrial area — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and its position as a major logistics hub on the A1(M) make it a key service location for Cambridgeshire.",
  "norwich": "Norwich's food processing, engineering, and construction industries — anchored by Broadland Business Park, Vulcan Road industrial area, and the Norwich Research Park — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The city's active commercial construction market and proximity to the A11 provide additional demand for mobile shot blasting services.",
  "ipswich": "Ipswich's port, logistics, and engineering industries — concentrated at the Port of Ipswich, Ransomes Europark, and the Whitehouse Industrial Estate — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The town's active commercial construction market and proximity to the A14 make it a key service location for Suffolk.",
  "luton": "Luton's airport, logistics, and manufacturing industries — anchored by London Luton Airport, Butterfield Business Park, and the Kimpton Road industrial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M1 and A1(M) make it a key service location for Bedfordshire.",
  "bedford": "Bedford's logistics, food processing, and construction industries — concentrated at Interchange Retail Park, Manton Lane industrial area, and the Elms Farm industrial estate — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A1 and M1 provide additional demand for mobile shot blasting services.",

  // ── South East ─────────────────────────────────────────────────────────────
  "brighton": "Brighton's construction, creative industries, and food processing sectors — anchored by the New England Quarter, Hollingbury Industrial Estate, and the ongoing Brighton Marina development — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A23 and A27 make it a key service location for East Sussex.",
  "reading": "Reading's technology, logistics, and construction industries — concentrated at Green Park Business Park, Winnersh Triangle, and the Thames Valley Park — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M4 make it a key service location for Berkshire.",
  "oxford": "Oxford's construction, biomedical, and technology sectors — anchored by the Oxford Science Park, Cowley industrial area, and the ongoing Oxford North development — generate consistent demand for structural steel shot blasting and surface preparation. The city's active commercial construction market and proximity to the A34 and M40 provide additional demand for mobile shot blasting services.",
  "southampton": "Southampton's port, marine engineering, and logistics industries — anchored by the Port of Southampton, Nursling Industrial Estate, and the Hedge End commercial area — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The city's active commercial construction market and proximity to the M3 and M27 make it a key service location for Hampshire.",
  "portsmouth": "Portsmouth's naval, marine engineering, and construction industries — concentrated at the Portsmouth Naval Base, Tipner industrial area, and the Lakeside North Harbour business park — generate consistent demand for structural steel shot blasting, marine surface preparation, and plant and machinery treatment. The city's active commercial construction market and proximity to the M27 provide additional demand for mobile shot blasting services.",
  "guildford": "Guildford's construction, technology, and logistics industries — anchored by Slyfield Industrial Estate, Guildford Business Park, and the Surrey Research Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A3 and M25 make it a key service location for Surrey.",
  "crawley": "Crawley's aviation, logistics, and manufacturing industries — concentrated at Gatwick Airport, Manor Royal Business District, and the Hazelwick Avenue industrial corridor — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M23 make it a key service location for West Sussex.",

  // ── London Fringe ──────────────────────────────────────────────────────────
  "watford": "Watford's logistics, film production, and construction industries — anchored by Croxley Business Park, Watford Business Park, and the Leavesden Studios complex — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M1 and M25 make it a key service location for Hertfordshire.",
  "st-albans": "St Albans' construction, logistics, and food processing industries — concentrated at Alban Park, Bricket Wood industrial area, and the Porters Wood business park — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the M1 and M25 provide additional demand for mobile shot blasting services.",
  "hertford": "Hertford's engineering, food processing, and construction industries — anchored by the Sele Farm industrial area, Gascoyne Way business park, and the Ware Road commercial corridor — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The town's active commercial construction market and proximity to the A10 and A414 make it a key service location for Hertfordshire.",

  // ── South West ─────────────────────────────────────────────────────────────
  "bristol": "Bristol's aerospace, engineering, and commercial construction sectors — anchored by Rolls-Royce's Filton campus, Airbus UK, and major regeneration projects at Temple Quarter and Bristol Harbourside — generate significant demand for precision surface preparation on structural steel, specialist fabrications, and factory cladding. The city's active commercial construction market and proximity to the M4 and M5 make it a key service location for the South West.",
  "bath": "Bath's construction, tourism infrastructure, and food processing industries — concentrated at the Riverside Business Park, Locksbrook Road industrial area, and the Keynsham commercial corridor — generate consistent demand for structural steel shot blasting, heritage metalwork restoration, and factory cladding preparation. The city's active commercial construction market and proximity to the M4 provide additional demand for mobile shot blasting services.",
  "swindon": "Swindon's automotive, logistics, and engineering industries — anchored by Honda's manufacturing plant at South Marston, the Greenbridge Retail Park, and Groundwell Industrial Estate — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M4 make it a key service location for Wiltshire.",
  "gloucester": "Gloucester's aerospace, engineering, and logistics industries — concentrated at Quedgeley Enterprise Centre, Gloucester Business Park, and the Barnwood industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M5 provide additional demand for mobile shot blasting services.",
  "cheltenham": "Cheltenham's GCHQ, technology, and construction sectors — anchored by Cheltenham Technology Park, Kingsditch Trading Estate, and the Arle Court business park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and specialist surface preparation. The town's active commercial construction market and proximity to the M5 make it a key service location for Gloucestershire.",
  "taunton": "Taunton's food processing, agricultural machinery, and construction industries — concentrated at Priorswood Industrial Estate, Tone Industrial Estate, and the Nexus 25 business park — generate steady demand for plant and machinery shot blasting, factory cladding restoration, and structural steelwork preparation. The town's active commercial construction market and proximity to the M5 provide additional demand for mobile shot blasting services.",

  // ── East Midlands / Lincolnshire ───────────────────────────────────────────
  "grimsby": "Grimsby's fishing, food processing, and offshore wind industries — anchored by the Grimsby Docks, Europarc business park, and the Humber Freeport zone — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The town's active commercial construction market and its role in the UK's offshore wind supply chain make it a key service location for Lincolnshire.",
  "scunthorpe": "Scunthorpe's steel manufacturing, engineering, and logistics industries — anchored by British Steel's Scunthorpe works, Normanby Enterprise Park, and the Queensway industrial area — generate consistent demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M180 make it a key service location for Lincolnshire.",

  // ── East Anglia ────────────────────────────────────────────────────────────
  "colchester": "Colchester's logistics, food processing, and construction industries — concentrated at Severalls Industrial Park, Hythe Quay, and the Stanway commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A12 and A120 make it a key service location for Essex.",
  "chelmsford": "Chelmsford's technology, logistics, and construction industries — anchored by Chelmsford City Centre regeneration, the Waterhouse Business Centre, and Boreham Airfield business park — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the A12 and M25 provide additional demand for mobile shot blasting services.",

  // ── North East ─────────────────────────────────────────────────────────────
  "newcastle": "Newcastle's construction, engineering, and logistics sectors — anchored by the Quayside regeneration zone, Team Valley Trading Estate, and the Newburn Riverside business park — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A1(M) and A19 make it a key service location for Tyne and Wear.",
  "sunderland": "Sunderland's automotive, glass manufacturing, and logistics industries — anchored by Nissan's Washington plant, the Sunderland Enterprise Park, and Doxford International Business Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A19 and A1(M) make it a key service location for Tyne and Wear.",
  "middlesbrough": "Middlesbrough's chemical, steel, and offshore engineering industries — concentrated at Teesside Industrial Estate, Wilton International, and the South Bank Quay — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and marine surface treatment. The town's active commercial construction market and proximity to the A66 and A19 make it a key service location for Teesside.",

  // ── Wales ──────────────────────────────────────────────────────────────────
  "cardiff": "Cardiff's construction, logistics, and food processing industries — anchored by the Cardiff Bay regeneration zone, Capital Business Park, and the Treforest Industrial Estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M4 make it a key service location for South Wales.",
  "swansea": "Swansea's port, manufacturing, and construction industries — concentrated at Swansea Vale Business Village, Llansamlet industrial area, and the Fabian Way commercial corridor — generate steady demand for structural steel shot blasting, container preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the M4 provide additional demand for mobile shot blasting services.",
  "newport": "Newport's logistics, steel manufacturing, and construction industries — anchored by the Newport Docks, Celtic Business Park, and the Queensway Meadows industrial estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M4 make it a key service location for South Wales.",

  // ── Scotland ───────────────────────────────────────────────────────────────
  "glasgow": "Glasgow's construction, engineering, and logistics sectors — anchored by the Clyde Gateway regeneration zone, Queenslie Industrial Estate, and the Hillington Park industrial area — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M8 and M74 make it a key service location for the Central Belt.",
  "edinburgh": "Edinburgh's construction, technology, and logistics industries — concentrated at Newbridge Industrial Estate, Sighthill industrial area, and the Edinburgh Park business campus — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M8 and M9 provide additional demand for mobile shot blasting services.",
};

/**
 * Generates a Local Industry Spotlight paragraph for a given town.
 * Returns the specific paragraph if available, otherwise generates a
 * county-context-aware fallback paragraph.
 */
export function getTownSpotlight(
  townSlug: string,
  townName: string,
  countyName: string,
  countySlug: string,
  region: string
): string | null {
  // Return specific spotlight if available
  if (townSpotlight[townSlug]) {
    return townSpotlight[townSlug];
  }

  // No spotlight for this town — return null to use countyContext fallback
  return null;
}
