/**
 * townSpotlight.ts
 * Unique "Local Industry Spotlight" paragraphs for the top ~80 highest-traffic
 * service-area towns. Each entry references specific local industrial estates,
 * business parks, employers, or infrastructure to differentiate the page content
 * for Google's quality threshold.
 *
 * For towns NOT in this map, generateTownSpotlight() falls back to a
 * county-context-aware template paragraph.
 */

export const townSpotlight: Record<string, string> = {
  // ── West Midlands ──────────────────────────────────────────────────────────
  "birmingham": "Birmingham's manufacturing corridor — stretching from Tyseley Industrial Estate through Aston and Smethwick — generates significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's ongoing HS2 construction programme and major commercial regeneration projects across Digbeth and the Jewellery Quarter provide consistent work for mobile shot blasting contractors serving the West Midlands.",
  "coventry": "Coventry's automotive and aerospace supply chain — anchored by the Manufacturing Technology Centre (MTC) at Ansty Park and major employers along the A45 industrial corridor — creates steady demand for precision surface preparation on structural steel, tooling, and specialist equipment. The city's ambitious regeneration of the city centre and Friargate business district also drives demand for commercial shot blasting services.",
  "wolverhampton": "Wolverhampton's industrial heritage is reflected in its active manufacturing base at i54 South Staffordshire and Pensnett Trading Estate, where engineering, automotive components, and fabrication businesses regularly require shot blasting and protective coating services. The city's ongoing commercial construction activity around the Waterfront and Stafford Road corridor provides additional demand for structural steelwork preparation.",
  "walsall": "Walsall's leather goods, metal finishing, and light engineering industries — concentrated around Darlaston and Bloxwich — generate consistent demand for shot blasting services on plant, machinery, and fabricated metalwork. The Birchley Island industrial area and Aldridge Business Park host a range of manufacturing businesses requiring regular surface preparation and protective coating maintenance.",
  "dudley": "Dudley's Black Country manufacturing heritage continues through active industrial estates at Pensnett, Brierley Hill, and Round Oak, where steel fabricators, engineering firms, and construction contractors regularly require shot blasting services. The Merry Hill commercial development and ongoing regeneration of the town centre also generate demand for structural steel and cladding restoration work.",

  // ── West Yorkshire ─────────────────────────────────────────────────────────
  "leeds": "Leeds is one of the UK's fastest-growing commercial construction markets, with major steel-framed developments across the South Bank, Wellington Place, and the wider city region generating consistent demand for structural steel shot blasting and surface preparation. The city's strong engineering, food processing, and logistics sectors — centred around Stourton, Hunslet, and Morley — also produce significant volumes of plant and machinery requiring specialist surface treatment.",
  "bradford": "Bradford's textile, engineering, and food manufacturing industries — concentrated in the Eureka Business Park, Bowling Back Lane industrial area, and Thornton Road corridor — generate steady demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The city's ongoing commercial regeneration and Bradford City Centre Masterplan projects provide additional demand for mobile shot blasting services.",
  "huddersfield": "Huddersfield's engineering and manufacturing base — including the Kirklees Light Railway, Crosland Moor industrial area, and the Penistone Road corridor — creates consistent demand for shot blasting services on structural steel, plant, and specialist fabrications. The town's proximity to the M62 and its role as a hub for West Yorkshire's manufacturing supply chain make it a key location for mobile shot blasting contractors.",
  "wakefield": "Wakefield's logistics, distribution, and manufacturing sectors — anchored by Normanton Industrial Estate, Calder Park, and the Wakefield Europort — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and ongoing regeneration of the Waterfront area provide additional work for mobile shot blasting services.",
  "halifax": "Halifax's engineering and manufacturing heritage — reflected in the Dean Clough industrial complex, Brighouse industrial area, and the Calder Valley manufacturing corridor — creates consistent demand for shot blasting services on structural steel, plant and machinery, and factory cladding. The town's active commercial property market and proximity to the M62 make it a key service location for West Yorkshire.",

  // ── South Yorkshire ────────────────────────────────────────────────────────
  "sheffield": "Sheffield's steel and advanced manufacturing heritage continues through active industrial clusters at Tinsley, Attercliffe, and the Advanced Manufacturing Park (AMP) at Waverley, where engineering firms, fabricators, and aerospace suppliers regularly require shot blasting and surface preparation services. The city's major commercial regeneration projects — including Heart of the City II and the Kelham Island district — also generate demand for structural steel and cladding restoration.",
  "rotherham": "Rotherham's steel fabrication, automotive, and logistics industries — concentrated at Templeborough, Parkgate, and the Advanced Manufacturing Park — generate significant demand for structural steel shot blasting, container preparation, and plant and machinery surface treatment. The town's proximity to the M1 and its role in South Yorkshire's manufacturing supply chain make it a key location for commercial shot blasting services.",
  "doncaster": "Doncaster's logistics, distribution, and manufacturing sectors — anchored by Doncaster Sheffield Airport Business Park, Balby Carr, and the iPort logistics hub — create consistent demand for structural steel shot blasting, warehouse racking preparation, and commercial vehicle surface treatment. The town's active construction market and ongoing regeneration of the city centre provide additional demand for mobile shot blasting services.",
  "barnsley": "Barnsley's manufacturing and engineering base — including the Dodworth Business Park, Wilthorpe industrial area, and the Dearne Valley Enterprise Zone — generates steady demand for shot blasting services on structural steel, plant and machinery, and factory cladding. The town's active commercial construction market and proximity to the M1 make it a key service location for South Yorkshire.",

  // ── Greater Manchester ─────────────────────────────────────────────────────
  "manchester": "Manchester's commercial construction boom — spanning Spinningfields, NOMA, and the wider city region — generates consistent demand for structural steel shot blasting and surface preparation. The city's strong engineering, food processing, and logistics sectors — centred around Trafford Park, Openshaw, and the Salford Quays — also produce significant volumes of plant and machinery requiring specialist surface treatment.",
  "salford": "Salford's MediaCityUK development and ongoing commercial regeneration of the Quays and Chapel Street corridor generate demand for structural steel shot blasting and cladding restoration. The city's traditional manufacturing base at Trafford Park — one of the UK's largest industrial estates — provides consistent work for mobile shot blasting contractors serving the Greater Manchester area.",
  "bolton": "Bolton's engineering, textiles, and food manufacturing industries — concentrated at Middlebrook Business Park, Lostock Industrial Estate, and the Chorley New Road corridor — generate steady demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The town's active commercial construction market and proximity to the M61 make it a key service location for Greater Manchester.",
  "oldham": "Oldham's manufacturing and engineering base — including the Chadderton industrial area, Hollinwood Business Centre, and the Broadway Business Park — creates consistent demand for shot blasting services on structural steel, plant and machinery, and factory cladding. The town's active commercial property market and proximity to the M60 orbital motorway make it a key location for mobile shot blasting services.",
  "rochdale": "Rochdale's engineering, textiles, and logistics industries — concentrated at Kingsway Business Park, Stakehill Industrial Estate, and the Heywood Distribution Park — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M62 provide additional demand for mobile shot blasting services.",

  // ── Merseyside ─────────────────────────────────────────────────────────────
  "liverpool": "Liverpool's port, logistics, and construction sectors — anchored by the Royal Seaforth Dock, Mersey Docks, and the Knowledge Quarter regeneration zone — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The city's active commercial construction market across Liverpool Waters and the Ten Streets district provides consistent work for mobile shot blasting contractors.",
  "birkenhead": "Birkenhead's shipbuilding heritage and active manufacturing base at Cammell Laird, Wirral International Business Park, and the Bidston industrial area generate consistent demand for structural steel shot blasting, marine surface preparation, and plant and machinery treatment. The town's proximity to the Mersey and its role in the North West's manufacturing supply chain make it a key location for commercial shot blasting services.",
  "st-helens": "St Helens' glass manufacturing, chemicals, and logistics industries — anchored by Pilkington's operations, Haydock Industrial Estate, and the Omega Business Park — generate steady demand for plant and machinery shot blasting, factory cladding restoration, and structural steelwork preparation. The town's active commercial construction market and proximity to the M6 and M62 make it a key service location for Merseyside.",

  // ── Lancashire ─────────────────────────────────────────────────────────────
  "blackburn": "Blackburn's engineering, textiles, and food manufacturing industries — concentrated at Shadsworth Business Park, Whitebirk Industrial Estate, and the Greenbank Technology Park — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The town's active commercial construction market and proximity to the M65 make it a key service location for Lancashire.",
  "burnley": "Burnley's aerospace, engineering, and manufacturing industries — anchored by the Burnley Bridge Business Park, Shuttleworth Mead Business Park, and the Heasandford Industrial Estate — create significant demand for precision surface preparation on structural steel, specialist fabrications, and plant and machinery. The town's role in the Lancashire aerospace supply chain makes it a key location for commercial shot blasting services.",
  "preston": "Preston's manufacturing, logistics, and construction sectors — concentrated at Walton Summit Industrial Estate, Cuerden Valley Business Park, and the Strand Road corridor — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the M6 and M65 provide additional demand for mobile shot blasting services.",

  // ── Cheshire ───────────────────────────────────────────────────────────────
  "chester": "Chester's construction, logistics, and food processing industries — anchored by Sealand Industrial Estate, Bumpers Lane industrial area, and the Wrexham Technology Park just across the border — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial property market and proximity to the A55 and M53 make it a key service location for Cheshire.",
  "warrington": "Warrington's logistics, chemicals, and manufacturing industries — concentrated at Birchwood Park, Gemini Retail Park, and the Woolston industrial area — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's position at the junction of the M6 and M62 makes it a central hub for commercial shot blasting services across the North West.",
  "crewe": "Crewe's railway engineering, automotive, and logistics industries — anchored by Bentley Motors' manufacturing plant, the Crewe Business Park, and the South Cheshire Growth Village — generate consistent demand for precision surface preparation on structural steel, specialist fabrications, and plant and machinery. The town's active commercial construction market and proximity to the M6 make it a key service location for Cheshire.",

  // ── East Midlands ──────────────────────────────────────────────────────────
  "nottingham": "Nottingham's pharmaceutical, engineering, and logistics industries — concentrated at Nottingham Business Park, Colwick Industrial Estate, and the Beeston industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market across the Waterside regeneration zone and Southside district provides additional demand for mobile shot blasting services.",
  "derby": "Derby's aerospace, rail engineering, and manufacturing industries — anchored by Rolls-Royce's manufacturing campus, Toyota's Burnaston plant, and the Raynesway industrial area — generate significant demand for precision surface preparation on structural steel, specialist fabrications, and plant and machinery. The city's active commercial construction market and proximity to the A38 and M1 make it a key service location for Derbyshire.",
  "leicester": "Leicester's textiles, food processing, and logistics industries — concentrated at Meridian Business Park, Optimus Point, and the Aylestone Road industrial corridor — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The city's active commercial construction market and proximity to the M1 and M69 provide additional demand for mobile shot blasting services.",
  "lincoln": "Lincoln's engineering, food processing, and agricultural machinery industries — concentrated at Whisby Road industrial area, Outer Circle Road, and the Tritton Road commercial corridor — generate consistent demand for plant and machinery shot blasting, structural steelwork preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the A46 provide additional demand for mobile shot blasting services.",

  // ── East of England ────────────────────────────────────────────────────────
  "cambridge": "Cambridge's technology, biomedical, and construction sectors — anchored by the Cambridge Science Park, Granta Park, and the ongoing Cambridge Biomedical Campus expansion — generate consistent demand for structural steel shot blasting and surface preparation. The city's active commercial construction market and the wider Cambridgeshire growth corridor provide significant demand for mobile shot blasting services.",
  "peterborough": "Peterborough's logistics, food processing, and construction industries — concentrated at Queensgate Business Park, Orton Southgate, and the Fengate industrial area — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and its position as a major logistics hub on the A1(M) make it a key service location for Cambridgeshire.",
  "norwich": "Norwich's food processing, engineering, and construction industries — anchored by Broadland Business Park, Vulcan Road industrial area, and the Norwich Research Park — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The city's active commercial construction market and proximity to the A11 provide additional demand for mobile shot blasting services.",
  "ipswich": "Ipswich's port, logistics, and engineering industries — concentrated at the Port of Ipswich, Ransomes Europark, and the Whitehouse Industrial Estate — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The town's active commercial construction market and proximity to the A14 make it a key service location for Suffolk.",
  "luton": "Luton's airport, logistics, and manufacturing industries — anchored by London Luton Airport, Butterfield Business Park, and the Kimpton Road industrial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M1 and A1(M) make it a key service location for Bedfordshire.",
  "bedford": "Bedford's logistics, food processing, and construction industries — concentrated at Interchange Retail Park, Manton Lane industrial area, and the Elms Farm industrial estate — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A1 and M1 provide additional demand for mobile shot blasting services.",

  // ── South East ─────────────────────────────────────────────────────────────
  "brighton": "Brighton's construction, creative industries, and food processing sectors — anchored by the New England Quarter, Hollingbury Industrial Estate, and the ongoing Brighton Marina development — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A23 and A27 make it a key service location for East Sussex.",
  "reading": "Reading's technology, logistics, and construction industries — concentrated at Green Park Business Park, Winnersh Triangle, and the Thames Valley Park — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M4 make it a key service location for Berkshire.",
  "oxford": "Oxford's construction, biomedical, and technology sectors — anchored by the Oxford Science Park, Cowley industrial area, and the ongoing Oxford North development — generate consistent demand for structural steel shot blasting and surface preparation. The city's active commercial construction market and proximity to the A34 and M40 provide additional demand for mobile shot blasting services.",
  "southampton": "Southampton's port, marine engineering, and logistics industries — anchored by the Port of Southampton, Nursling Industrial Estate, and the Hedge End commercial area — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The city's active commercial construction market and proximity to the M3 and M27 make it a key service location for Hampshire.",
  "portsmouth": "Portsmouth's naval, marine engineering, and construction industries — concentrated at the Portsmouth Naval Base, Tipner industrial area, and the Lakeside North Harbour business park — generate consistent demand for structural steel shot blasting, marine surface preparation, and plant and machinery treatment. The city's active commercial construction market and proximity to the M27 provide additional demand for mobile shot blasting services.",
  "crawley": "Crawley's aviation, logistics, and manufacturing industries — concentrated at Gatwick Airport, Manor Royal Business District, and the Hazelwick Avenue industrial corridor — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M23 make it a key service location for West Sussex.",

  // ── London Fringe ──────────────────────────────────────────────────────────
  "watford": "Watford's logistics, film production, and construction industries — anchored by Croxley Business Park, Watford Business Park, and the Leavesden Studios complex — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M1 and M25 make it a key service location for Hertfordshire.",
  "st-albans": "St Albans' construction, logistics, and food processing industries — concentrated at Alban Park, Bricket Wood industrial area, and the Porters Wood business park — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the M1 and M25 provide additional demand for mobile shot blasting services.",
  "hertford": "Hertford's engineering, food processing, and construction industries — anchored by the Sele Farm industrial area, Gascoyne Way business park, and the Ware Road commercial corridor — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The town's active commercial construction market and proximity to the A10 and A414 make it a key service location for Hertfordshire.",

  // ── South West ─────────────────────────────────────────────────────────────
  "bristol": "Bristol's aerospace, engineering, and commercial construction sectors — anchored by Rolls-Royce's Filton campus, Airbus UK, and major regeneration projects at Temple Quarter and Bristol Harbourside — generate significant demand for precision surface preparation on structural steel, specialist fabrications, and factory cladding. The city's active commercial construction market and proximity to the M4 and M5 make it a key service location for the South West.",
  "bath": "Bath's construction, tourism infrastructure, and food processing industries — concentrated at the Riverside Business Park, Locksbrook Road industrial area, and the Keynsham commercial corridor — generate consistent demand for structural steel shot blasting, heritage metalwork restoration, and factory cladding preparation. The city's active commercial construction market and proximity to the M4 provide additional demand for mobile shot blasting services.",
  "swindon": "Swindon's automotive, logistics, and engineering industries — anchored by Honda's manufacturing plant at South Marston, the Greenbridge Retail Park, and Groundwell Industrial Estate — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M4 make it a key service location for Wiltshire.",
  "gloucester": "Gloucester's aerospace, engineering, and logistics industries — concentrated at Quedgeley Enterprise Centre, Gloucester Business Park, and the Barnwood industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M5 provide additional demand for mobile shot blasting services.",
  "cheltenham": "Cheltenham's GCHQ, technology, and construction sectors — anchored by Cheltenham Technology Park, Kingsditch Trading Estate, and the Arle Court business park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and specialist surface preparation. The town's active commercial construction market and proximity to the M5 make it a key service location for Gloucestershire.",
  "taunton": "Taunton's food processing, agricultural machinery, and construction industries — concentrated at Priorswood Industrial Estate, Tone Industrial Estate, and the Nexus 25 business park — generate steady demand for plant and machinery shot blasting, factory cladding restoration, and structural steelwork preparation. The town's active commercial construction market and proximity to the M5 provide additional demand for mobile shot blasting services.",

  // ── East Midlands / Lincolnshire ───────────────────────────────────────────
  "grimsby": "Grimsby's fishing, food processing, and offshore wind industries — anchored by the Grimsby Docks, Europarc business park, and the Humber Freeport zone — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The town's active commercial construction market and its role in the UK's offshore wind supply chain make it a key service location for Lincolnshire.",
  "scunthorpe": "Scunthorpe's steel manufacturing, engineering, and logistics industries — anchored by British Steel's Scunthorpe works, Normanby Enterprise Park, and the Queensway industrial area — generate consistent demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M180 make it a key service location for Lincolnshire.",

  // ── East Anglia ────────────────────────────────────────────────────────────
  "colchester": "Colchester's logistics, food processing, and construction industries — concentrated at Severalls Industrial Park, Hythe Quay, and the Stanway commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A12 and A120 make it a key service location for Essex.",
  "chelmsford": "Chelmsford's technology, logistics, and construction industries — anchored by Chelmsford City Centre regeneration, the Waterhouse Business Centre, and Boreham Airfield business park — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the A12 and M25 provide additional demand for mobile shot blasting services.",

  // ── North East ─────────────────────────────────────────────────────────────
  "newcastle": "Newcastle's construction, engineering, and logistics sectors — anchored by the Quayside regeneration zone, Team Valley Trading Estate, and the Newburn Riverside business park — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A1(M) and A19 make it a key service location for Tyne and Wear.",
  "sunderland": "Sunderland's automotive, glass manufacturing, and logistics industries — anchored by Nissan's Washington plant, the Sunderland Enterprise Park, and Doxford International Business Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A19 and A1(M) make it a key service location for Tyne and Wear.",
  "middlesbrough": "Middlesbrough's chemical, steel, and offshore engineering industries — concentrated at Teesside Industrial Estate, Wilton International, and the South Bank Quay — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and marine surface treatment. The town's active commercial construction market and proximity to the A66 and A19 make it a key service location for Teesside.",

  // ── Wales ──────────────────────────────────────────────────────────────────
  "cardiff": "Cardiff's construction, logistics, and food processing industries — anchored by the Cardiff Bay regeneration zone, Capital Business Park, and the Treforest Industrial Estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M4 make it a key service location for South Wales.",
  "swansea": "Swansea's port, manufacturing, and construction industries — concentrated at Swansea Vale Business Village, Llansamlet industrial area, and the Fabian Way commercial corridor — generate steady demand for structural steel shot blasting, container preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the M4 provide additional demand for mobile shot blasting services.",
  "newport": "Newport's logistics, steel manufacturing, and construction industries — anchored by the Newport Docks, Celtic Business Park, and the Queensway Meadows industrial estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M4 make it a key service location for South Wales.",

  // ── Scotland ───────────────────────────────────────────────────────────────
  "glasgow": "Glasgow's construction, engineering, and logistics sectors — anchored by the Clyde Gateway regeneration zone, Queenslie Industrial Estate, and the Hillington Park industrial area — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M8 and M74 make it a key service location for the Central Belt.",
  "edinburgh": "Edinburgh's construction, technology, and logistics industries — concentrated at Newbridge Industrial Estate, Sighthill industrial area, and the Edinburgh Park business campus — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M8 and M9 provide additional demand for mobile shot blasting services.",

  // ── Tier-2 Towns (100 additional entries) ─────────────────────────────────
// ── Staffordshire ─────────────────────────────────────────────────────────
  "stoke-on-trent": "Stoke-on-Trent's ceramics, advanced manufacturing, and logistics industries — anchored by Wedgwood's Barlaston site, the Trentham Lakes business park, and Fenton Industrial Estate — generate consistent demand for plant and machinery shot blasting, factory cladding restoration, and structural steelwork preparation. The city's active commercial construction market and proximity to the M6 and A500 make it a key service location for Staffordshire.",

  "stafford": "Stafford's engineering, logistics, and construction industries — concentrated at Stafford Park, Beacon Business Park, and the Tollgate Drive industrial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M6 and A34 make it a key service location for Staffordshire.",

  "tamworth": "Tamworth's logistics, retail distribution, and manufacturing industries — anchored by the Ventura Retail Park, Relay Park business park, and the Lichfield Road industrial corridor — generate consistent demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M42 and A5 make it a key service location for Staffordshire.",

  "cannock": "Cannock's mining heritage, logistics, and manufacturing industries — concentrated at Kingswood Lakeside, Hawks Green industrial area, and the Orbital Retail Park — generate steady demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M6 Toll and A5 provide additional demand for mobile shot blasting services.",

  "newcastle-under-lyme": "Newcastle-under-Lyme's ceramics, logistics, and construction industries — anchored by Lymedale Business Park, Parkhouse Industrial Estate, and the Chesterton industrial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M6 and A34 make it a key service location for Staffordshire.",

  // ── West Midlands ─────────────────────────────────────────────────────────
  "solihull": "Solihull's automotive, aerospace, and logistics industries — anchored by Land Rover's Lode Lane plant, the NEC complex, and Birmingham Business Park — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The borough's active commercial construction market and proximity to the M42 and M6 make it a key service location for the West Midlands.",

  "kidderminster": "Kidderminster's carpet manufacturing, engineering, and logistics industries — concentrated at Stourport Road industrial area, Churchfields Business Park, and the Carpet Trade Park — generate consistent demand for factory cladding restoration, plant and machinery shot blasting, and structural steelwork preparation. The town's active commercial construction market and proximity to the A456 and M5 make it a key service location for Worcestershire.",

  "brierley-hill": "Brierley Hill's steel fabrication, glass, and logistics industries — anchored by the Merry Hill shopping complex, Waterfront Business Park, and the Pensnett Trading Estate — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A461 and M5 make it a key service location for the Black Country.",

  "aldridge": "Aldridge's engineering, logistics, and construction industries — concentrated at Aldridge Business Park, Middleton Road industrial area, and the Anchor Road commercial corridor — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M6 Toll and A452 provide additional demand for mobile shot blasting services.",

  // ── Worcestershire ────────────────────────────────────────────────────────
  "worcester": "Worcester's engineering, food processing, and construction industries — anchored by Shrub Hill Industrial Estate, Blackpole Trading Estate, and the Lowesmoor Wharf commercial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M5 and A38 make it a key service location for Worcestershire.",

  "redditch": "Redditch's automotive components, engineering, and logistics industries — concentrated at Ravensbank Business Park, Moons Moat Industrial Estate, and the Washford Industrial Estate — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M42 and A441 make it a key service location for Worcestershire.",

  "bromsgrove": "Bromsgrove's engineering, logistics, and construction industries — anchored by Buntsford Gate Business Park, Aston Fields Industrial Estate, and the Charford Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M42 and M5 make it a key service location for Worcestershire.",

  // ── Warwickshire ──────────────────────────────────────────────────────────
  "nuneaton": "Nuneaton's automotive, logistics, and engineering industries — anchored by Bermuda Park, Newdigate Colliery Business Park, and the Attleborough Fields Industrial Estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M6 and A444 make it a key service location for Warwickshire.",

  "rugby": "Rugby's engineering, logistics, and construction industries — concentrated at Butlers Leap Industrial Estate, Hillmorton Road industrial area, and the Rugby Gateway distribution park — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M1 and M6 make it a key service location for Warwickshire.",

  "leamington-spa": "Leamington Spa's automotive technology, engineering, and construction industries — anchored by Tachbrook Park, Heathcote Industrial Estate, and the Sydenham Industrial Estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M40 and A46 make it a key service location for Warwickshire.",

  "warwick": "Warwick's engineering, logistics, and construction industries — concentrated at Wedgnock Industrial Estate, Budbrooke Industrial Estate, and the Cape Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M40 and A46 provide additional demand for mobile shot blasting services.",

  // ── Northamptonshire ──────────────────────────────────────────────────────
  "northampton": "Northampton's logistics, footwear manufacturing, and construction industries — anchored by Brackmills Industrial Estate, Swan Valley distribution park, and the Moulton Park Business Centre — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M1 and A45 make it a key service location for Northamptonshire.",

  "kettering": "Kettering's logistics, engineering, and construction industries — concentrated at Telford Way Industrial Estate, Pytchley Lodge Road industrial area, and the Kettering Venture Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A14 and A43 make it a key service location for Northamptonshire.",

  "corby": "Corby's steel manufacturing, logistics, and construction industries — anchored by Corby Business Academy, Earlstrees Industrial Estate, and the Weldon Road industrial corridor — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A14 and A43 make it a key service location for Northamptonshire.",

  "wellingborough": "Wellingborough's logistics, food processing, and engineering industries — concentrated at Denington Industrial Estate, Finedon Road Industrial Estate, and the Niort Way commercial corridor — generate consistent demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A45 and A509 make it a key service location for Northamptonshire.",

  // ── Leicestershire ────────────────────────────────────────────────────────

  "hinckley": "Hinckley's automotive components, logistics, and engineering industries — concentrated at Dodwells Bridge Industrial Estate, Tungsten Park, and the Coventry Road commercial corridor — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M69 and A5 make it a key service location for Leicestershire.",

  "market-harborough": "Market Harborough's food processing, logistics, and construction industries — anchored by Airfield Industrial Estate, Rockingham Road industrial area, and the Great Bowden Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A6 and A508 provide additional demand for mobile shot blasting services.",

  "loughborough": "Loughborough's engineering, technology, and construction industries — anchored by Loughborough University Science and Enterprise Park, Charnwood Business Park, and the Shelthorpe Road industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M1 and A6 make it a key service location for Leicestershire.",

  // ── Nottinghamshire ───────────────────────────────────────────────────────
  "mansfield": "Mansfield's engineering, logistics, and construction industries — concentrated at Oakham Business Park, Berry Hill Industrial Estate, and the Nottingham Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A38 and M1 make it a key service location for Nottinghamshire.",

  "worksop": "Worksop's logistics, food processing, and engineering industries — anchored by Shireoaks Industrial Estate, Claylands Avenue industrial area, and the Retford Road commercial corridor — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A57 and A1 provide additional demand for mobile shot blasting services.",

  "newark": "Newark's food processing, engineering, and logistics industries — concentrated at Brunel Drive Industrial Estate, Northgate industrial area, and the Showground Business Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A1 and A46 make it a key service location for Nottinghamshire.",

  // ── Derbyshire ────────────────────────────────────────────────────────────
  "chesterfield": "Chesterfield's engineering, logistics, and construction industries — anchored by Sheepbridge Business Park, Whittington Moor industrial area, and the Markham Vale Enterprise Zone — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M1 and A61 make it a key service location for Derbyshire.",

  "ilkeston": "Ilkeston's engineering, textiles, and logistics industries — concentrated at Manners Industrial Estate, Hallam Fields Road industrial area, and the Stanton Road commercial corridor — generate consistent demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M1 and A609 make it a key service location for Derbyshire.",

  "buxton": "Buxton's quarrying, tourism infrastructure, and construction industries — anchored by Staden Lane Industrial Estate, Buxton Business Centre, and the Spring Gardens commercial area — generate steady demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A6 and A537 provide additional demand for mobile shot blasting services.",

  // ── Lincolnshire ──────────────────────────────────────────────────────────
  "grantham": "Grantham's food processing, engineering, and logistics industries — concentrated at Alma Park Industrial Estate, Springfield Business Park, and the Dysart Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A1 and A52 make it a key service location for Lincolnshire.",

  "boston": "Boston's food processing, agricultural machinery, and port industries — anchored by Endeavour Park, Marsh Lane industrial area, and the South Forty Foot Drain commercial corridor — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and container preparation. The town's active commercial construction market and proximity to the A16 and A17 make it a key service location for Lincolnshire.",

  "spalding": "Spalding's food processing, agricultural, and logistics industries — concentrated at Wardentree Park, Pinchbeck Road industrial area, and the Holland Market commercial area — generate consistent demand for plant and machinery shot blasting, factory cladding restoration, and structural steelwork preparation. The town's active commercial construction market and proximity to the A16 and A151 provide additional demand for mobile shot blasting services.",

  // ── Shropshire ────────────────────────────────────────────────────────────
  "shrewsbury": "Shrewsbury's engineering, food processing, and construction industries — anchored by Battlefield Enterprise Park, Harlescott Industrial Estate, and the Shrewsbury Business Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M54 and A5 make it a key service location for Shropshire.",

  "telford": "Telford's automotive, engineering, and logistics industries — concentrated at Hortonwood Industrial Estate, Stafford Park, and the Halesfield industrial area — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M54 and A5 make it a key service location for Shropshire.",

  "bridgnorth": "Bridgnorth's engineering, food processing, and construction industries — anchored by Faraday Drive industrial area, Stanmore Industrial Estate, and the Bridgnorth Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A458 and A442 provide additional demand for mobile shot blasting services.",

  // ── Herefordshire ─────────────────────────────────────────────────────────
  "hereford": "Hereford's food processing, agricultural machinery, and construction industries — concentrated at Rotherwas Industrial Estate, Holmer Road industrial area, and the Thorn Business Park — generate consistent demand for plant and machinery shot blasting, structural steel surface preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the A49 and A465 make it a key service location for Herefordshire.",

  // ── Cheshire ──────────────────────────────────────────────────────────────
  "macclesfield": "Macclesfield's pharmaceutical, engineering, and logistics industries — anchored by Hurdsfield Industrial Estate, Lyme Green Business Park, and the Tytherington Business Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M6 and A523 make it a key service location for Cheshire.",

  "ellesmere-port": "Ellesmere Port's petrochemical, automotive, and logistics industries — concentrated at Vauxhall's Ellesmere Port plant, Rossmore Industrial Estate, and the Stanlow Oil Refinery complex — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and industrial pipeline treatment. The town's active commercial construction market and proximity to the M53 and M56 make it a key service location for Cheshire.",

  "runcorn": "Runcorn's chemical, logistics, and construction industries — anchored by Runcorn Industrial Estate, Astmoor Industrial Estate, and the Mersey Gateway business corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M56 and A557 make it a key service location for Cheshire.",

  "widnes": "Widnes's chemical, logistics, and engineering industries — concentrated at Widnes Business Park, Simm's Cross industrial area, and the Mersey Road commercial corridor — generate steady demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M62 and A557 provide additional demand for mobile shot blasting services.",

  "congleton": "Congleton's textiles, engineering, and logistics industries — anchored by Radnor Park Industrial Estate, Daneside Business Park, and the Mountbatten Way commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M6 and A34 make it a key service location for Cheshire.",

  // ── Greater Manchester ────────────────────────────────────────────────────
  "stockport": "Stockport's engineering, logistics, and construction industries — concentrated at Bredbury Industrial Estate, Portwood Industrial Estate, and the Cheadle Royal Business Park — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M60 and M63 make it a key service location for Greater Manchester.",

  // ── West Yorkshire ────────────────────────────────────────────────────────
  "batley": "Batley's textiles, logistics, and engineering industries — anchored by Batley Business Park, Soothill Lane industrial area, and the Birstall Retail Park commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M62 and A652 make it a key service location for West Yorkshire.",

  "brighouse": "Brighouse's engineering, textiles, and logistics industries — concentrated at Armytage Road Industrial Estate, Brighouse Business Village, and the Clifton Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M62 and A641 provide additional demand for mobile shot blasting services.",

  "castleford": "Castleford's chemicals, glass, and logistics industries — anchored by Glasshoughton Business Park, Whitwood Industrial Estate, and the Methley Road commercial corridor — generate consistent demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M62 and A656 make it a key service location for West Yorkshire.",

  "dewsbury": "Dewsbury's textiles, engineering, and logistics industries — concentrated at Savile Town Industrial Estate, Calder Road industrial area, and the Dewsbury Retail Park commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M62 and A638 make it a key service location for West Yorkshire.",

  // ── South Yorkshire ───────────────────────────────────────────────────────
  "worsbrough": "Worsbrough's engineering, logistics, and construction industries — anchored by Worsbrough Bridge industrial area, Birdwell Business Park, and the Sheffield Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The area's active commercial construction market and proximity to the M1 and A61 provide additional demand for mobile shot blasting services.",

  // ── Buckinghamshire ───────────────────────────────────────────────────────
  "milton-keynes": "Milton Keynes's logistics, technology, and construction industries — anchored by Magna Park, Campbell Park Business Centre, and the Linford Wood industrial area — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The city's active commercial construction market and proximity to the M1 and A5 make it a key service location for Buckinghamshire.",

  "aylesbury": "Aylesbury's logistics, food processing, and construction industries — concentrated at Gatehouse Way industrial area, Rabans Lane Business Park, and the Stocklake industrial estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A41 and M25 make it a key service location for Buckinghamshire.",

  "high-wycombe": "High Wycombe's furniture manufacturing, logistics, and construction industries — anchored by Cressex Business Park, Wycombe Marsh industrial area, and the Sands Industrial Estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M40 and A40 make it a key service location for Buckinghamshire.",

  // ── Hertfordshire ─────────────────────────────────────────────────────────
  "stevenage": "Stevenage's aerospace, defence, and engineering industries — anchored by MBDA's Gunnels Wood Road campus, Airbus UK, and the Cavendish Road industrial area — generate significant demand for structural steel shot blasting, factory cladding restoration, and precision surface preparation. The town's active commercial construction market and proximity to the A1(M) make it a key service location for Hertfordshire.",

  "hemel-hempstead": "Hemel Hempstead's logistics, printing, and construction industries — concentrated at Maylands Business Park, Swallowdale Lane industrial area, and the Jarman Park commercial corridor — generate consistent demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M1 and M25 make it a key service location for Hertfordshire.",

  // ── Bedfordshire ──────────────────────────────────────────────────────────
  "dunstable": "Dunstable's logistics, manufacturing, and construction industries — anchored by Woodside Industrial Estate, Porz Avenue industrial area, and the Dunstable Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M1 and A5 make it a key service location for Bedfordshire.",

  "leighton-buzzard": "Leighton Buzzard's sand quarrying, logistics, and construction industries — concentrated at Grovebury Road Industrial Estate, Billington Road industrial area, and the Lake Street commercial corridor — generate steady demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M1 and A5 provide additional demand for mobile shot blasting services.",

  // ── Cambridgeshire ────────────────────────────────────────────────────────
  "ely": "Ely's food processing, agricultural, and construction industries — anchored by Lancaster Way Business Park, Ely Business Park, and the Downham Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A10 and A142 make it a key service location for Cambridgeshire.",

  "huntingdon": "Huntingdon's logistics, food processing, and engineering industries — concentrated at Stukeley Meadows Industrial Estate, Ermine Business Park, and the Brampton Road commercial corridor — generate steady demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A14 and A1 provide additional demand for mobile shot blasting services.",

  // ── Norfolk ───────────────────────────────────────────────────────────────
  "kings-lynn": "King's Lynn's port, food processing, and logistics industries — anchored by the Port of King's Lynn, Hardwick Industrial Estate, and the Saddlebow Road commercial corridor — generate significant demand for structural steel shot blasting, container preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A47 and A10 make it a key service location for Norfolk.",

  "great-yarmouth": "Great Yarmouth's offshore energy, tourism infrastructure, and port industries — concentrated at South Denes Industrial Estate, Outer Harbour, and the Gapton Hall Retail Park — generate significant demand for structural steel shot blasting, marine surface preparation, and plant and machinery treatment. The town's active commercial construction market and its role in the North Sea energy supply chain make it a key service location for Norfolk.",

  "thetford": "Thetford's food processing, engineering, and logistics industries — anchored by Thetford Industrial Estate, Mundford Road industrial area, and the Burrell Way commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A11 and A134 make it a key service location for Norfolk.",

  // ── Suffolk ───────────────────────────────────────────────────────────────
  "bury-st-edmunds": "Bury St Edmunds's food processing, brewing, and logistics industries — concentrated at Moreton Hall Industrial Estate, Rougham Hill industrial area, and the Fornham Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A14 and A143 make it a key service location for Suffolk.",

  "lowestoft": "Lowestoft's offshore energy, fishing, and port industries — anchored by the Port of Lowestoft, Mobbs Way industrial area, and the East Suffolk Business Centre — generate significant demand for structural steel shot blasting, marine surface preparation, and container treatment. The town's active commercial construction market and its role in the East Anglian offshore wind supply chain make it a key service location for Suffolk.",

  "felixstowe": "Felixstowe's port, logistics, and construction industries — concentrated at the Port of Felixstowe (the UK's busiest container port), Dock Road industrial area, and the Ransomes Europark — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The town's active commercial construction market and proximity to the A14 make it a key service location for Suffolk.",

  // ── Essex ─────────────────────────────────────────────────────────────────
  "southend-on-sea": "Southend-on-Sea's aviation, logistics, and construction industries — anchored by London Southend Airport, Southend Airport Business Park, and the Priory Crescent industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A127 and A13 make it a key service location for Essex.",

  "basildon": "Basildon's automotive, logistics, and engineering industries — concentrated at Burnt Mills Industrial Estate, Pipps Hill Industrial Estate, and the Laindon Links business park — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A127 and M25 make it a key service location for Essex.",

  "harlow": "Harlow's pharmaceutical, engineering, and logistics industries — anchored by Templefields Industrial Estate, Pinnacles Business Park, and the River Way industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M11 and A414 make it a key service location for Essex.",

  // ── Kent ──────────────────────────────────────────────────────────────────
  "maidstone": "Maidstone's logistics, food processing, and construction industries — concentrated at Parkwood Industrial Estate, Tovil industrial area, and the Allington Way commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M20 and M2 make it a key service location for Kent.",

  "medway": "Medway's naval, engineering, and logistics industries — anchored by Chatham Dockyard, Medway City Estate, and the Strood Retail Park commercial area — generate significant demand for structural steel shot blasting, marine surface preparation, and factory cladding restoration. The conurbation's active commercial construction market and proximity to the M2 and M20 make it a key service location for Kent.",

  "folkestone": "Folkestone's port, logistics, and construction industries — concentrated at the Channel Tunnel terminal, Folkestone Harbour, and the Shearway Business Park — generate consistent demand for structural steel shot blasting, container preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M20 make it a key service location for Kent.",

  "dover": "Dover's port, logistics, and construction industries — anchored by the Port of Dover (the UK's busiest ferry port), Whitfield Industrial Estate, and the Crabble Road commercial corridor — generate significant demand for structural steel shot blasting, container preparation, and marine surface treatment. The town's active commercial construction market and proximity to the M20 and A2 make it a key service location for Kent.",

  // ── East Sussex ───────────────────────────────────────────────────────────
  "eastbourne": "Eastbourne's construction, tourism infrastructure, and food processing industries — concentrated at Lottbridge Drove Industrial Estate, Eastbourne Harbour, and the Birch Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A22 and A27 make it a key service location for East Sussex.",

  "hastings": "Hastings's construction, fishing, and tourism infrastructure industries — anchored by the Ridge West Business Park, Queensway Industrial Estate, and the Bohemia Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A21 and A259 provide additional demand for mobile shot blasting services.",

  // ── West Sussex ───────────────────────────────────────────────────────────
  "worthing": "Worthing's logistics, food processing, and construction industries — concentrated at Dominion Way industrial area, Broadwater Business Park, and the Lyons Way commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A27 and A24 make it a key service location for West Sussex.",

  "chichester": "Chichester's construction, aviation, and food processing industries — anchored by Terminus Road Industrial Estate, Portfield industrial area, and the Tangmere Business Park — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A27 and A3(M) provide additional demand for mobile shot blasting services.",

  // ── Gloucestershire ───────────────────────────────────────────────────────
  "stroud": "Stroud's textiles, engineering, and construction industries — concentrated at Brimscombe Port Business Park, Lightpill industrial area, and the Merrywalks commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M5 and A419 make it a key service location for Gloucestershire.",

  "cirencester": "Cirencester's logistics, construction, and food processing industries — anchored by Cirencester Business Park, Love Lane industrial area, and the Tetbury Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A417 and A419 provide additional demand for mobile shot blasting services.",

  // ── Somerset ──────────────────────────────────────────────────────────────
  "weston-super-mare": "Weston-super-Mare's aerospace, logistics, and construction industries — anchored by Helicopter Museum, Oldmixon Industrial Estate, and the Winterstoke Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M5 and A370 make it a key service location for Somerset.",

  "yeovil": "Yeovil's aerospace, engineering, and construction industries — concentrated at Westland Helicopters' Yeovil site, Lynx Trading Estate, and the Boundary Road industrial area — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A303 and A30 make it a key service location for Somerset.",

  "bridgwater": "Bridgwater's energy, logistics, and construction industries — anchored by the Hinkley Point C nuclear construction site, Colley Lane Industrial Estate, and the Dunball Wharf commercial area — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M5 and A38 make it a key service location for Somerset.",

  // ── Wiltshire ─────────────────────────────────────────────────────────────
  "salisbury": "Salisbury's defence, construction, and food processing industries — concentrated at Churchfields Industrial Estate, Bourne Valley Road industrial area, and the Bourne Hill commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the A303 and A36 make it a key service location for Wiltshire.",

  "chippenham": "Chippenham's engineering, logistics, and construction industries — anchored by Bumpers Farm Industrial Estate, Methuen Park, and the Cocklebury Road industrial area — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M4 and A350 make it a key service location for Wiltshire.",

  "trowbridge": "Trowbridge's food processing, engineering, and construction industries — concentrated at Bythesea Road industrial area, Stallard Street commercial corridor, and the West Wiltshire Trading Estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A350 and A361 make it a key service location for Wiltshire.",

  // ── Devon ─────────────────────────────────────────────────────────────────
  "exeter": "Exeter's aerospace, logistics, and construction industries — anchored by Exeter Airport Business Park, Marsh Barton Industrial Estate, and the Sowton Industrial Estate — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M5 and A30 make it a key service location for Devon.",

  "plymouth": "Plymouth's naval, marine engineering, and construction industries — concentrated at Devonport Naval Base, Cattedown Wharves, and the Estover Industrial Estate — generate significant demand for structural steel shot blasting, marine surface preparation, and plant and machinery treatment. The city's active commercial construction market and proximity to the A38 make it a key service location for Devon.",

  "barnstaple": "Barnstaple's food processing, agricultural machinery, and construction industries — anchored by Pottington Business Park, Roundswell Business Park, and the Seven Brethren industrial area — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A361 and A39 make it a key service location for North Devon.",

  // ── Dorset ────────────────────────────────────────────────────────────────
  "bournemouth": "Bournemouth's aviation, technology, and construction industries — concentrated at Bournemouth Airport, Merrifield Industrial Estate, and the Yeomans Way commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The conurbation's active commercial construction market and proximity to the A338 and A31 make it a key service location for Dorset.",

  "poole": "Poole's marine engineering, logistics, and construction industries — anchored by the Port of Poole, Fleets Bridge Industrial Estate, and the Nuffield Industrial Estate — generate significant demand for structural steel shot blasting, marine surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A31 and A35 make it a key service location for Dorset.",

  "weymouth": "Weymouth's port, tourism infrastructure, and construction industries — concentrated at Granby Industrial Estate, Weymouth Harbour, and the Lynch Lane commercial corridor — generate steady demand for structural steel shot blasting, marine surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the A354 and A35 provide additional demand for mobile shot blasting services.",

  // ── East Wales ────────────────────────────────────────────────────────────
  "wrexham": "Wrexham's manufacturing, logistics, and construction industries — anchored by Wrexham Industrial Estate (one of the largest in Wales), Redwither Business Park, and the Clywedog Road commercial corridor — generate significant demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A483 and M53 make it a key service location for North Wales.",

  "merthyr-tydfil": "Merthyr Tydfil's engineering, logistics, and construction industries — concentrated at Pentrebach Industrial Estate, Rhydycar Business Park, and the Swansea Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A470 and A465 make it a key service location for South Wales.",

  "bridgend": "Bridgend's automotive, logistics, and construction industries — anchored by Ford's Bridgend engine plant, Bridgend Industrial Estate, and the Waterton Industrial Estate — generate significant demand for structural steel shot blasting, plant and machinery surface preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M4 make it a key service location for South Wales.",

  // ── Berkshire ─────────────────────────────────────────────────────────────
  "slough": "Slough's logistics, technology, and construction industries — anchored by Slough Trading Estate (one of Europe's largest business parks), Farnham Road industrial area, and the Cippenham commercial corridor — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M4 and M25 make it a key service location for Berkshire.",

  // ── Oxfordshire ───────────────────────────────────────────────────────────
  "banbury": "Banbury's food processing, automotive, and logistics industries — concentrated at Bankside Industrial Estate, Wildmere Road industrial area, and the Cherwell Valley Business Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M40 and A361 make it a key service location for Oxfordshire.",

  // ── Hampshire ─────────────────────────────────────────────────────────────
  "basingstoke": "Basingstoke's logistics, technology, and construction industries — anchored by Basing View Business Park, Viables Industrial Estate, and the Houndmills Road industrial area — generate significant demand for structural steel shot blasting, warehouse racking preparation, and factory cladding restoration. The town's active commercial construction market and proximity to the M3 and A30 make it a key service location for Hampshire.",

  "andover": "Andover's logistics, food processing, and construction industries — concentrated at Walworth Business Park, Portway Industrial Estate, and the Charlton Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A303 and A343 make it a key service location for Hampshire.",

  // ── Surrey ────────────────────────────────────────────────────────────────
  "guildford": "Guildford's technology, logistics, and construction industries — anchored by Slyfield Industrial Estate, Woodbridge Meadows industrial area, and the Guildford Business Park — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the A3 and M25 make it a key service location for Surrey.",

  "woking": "Woking's technology, logistics, and construction industries — concentrated at Woking Business Park, Sheerwater Industrial Estate, and the Goldsworth Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M25 and A3 provide additional demand for mobile shot blasting services.",

  // ── Lancashire ────────────────────────────────────────────────────────────
  "lancaster": "Lancaster's healthcare, logistics, and construction industries — anchored by Lansil Industrial Estate, White Lund Industrial Estate, and the Caton Road commercial corridor — generate consistent demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The city's active commercial construction market and proximity to the M6 and A6 make it a key service location for Lancashire.",

  "accrington": "Accrington's textiles, engineering, and logistics industries — concentrated at Hyndburn Road industrial area, Huncoat Industrial Estate, and the Whalley Road commercial corridor — generate steady demand for structural steel shot blasting, factory cladding restoration, and plant and machinery surface preparation. The town's active commercial construction market and proximity to the M65 and A679 provide additional demand for mobile shot blasting services.",

  // ── Cumbria ───────────────────────────────────────────────────────────────
  "barrow-in-furness": "Barrow-in-Furness's naval shipbuilding, nuclear, and engineering industries — anchored by BAE Systems Submarine Solutions, Devonshire Dock Hall, and the Hindpool Road industrial area — generate significant demand for structural steel shot blasting, marine surface preparation, and plant and machinery treatment. The town's active commercial construction market and proximity to the A590 make it a key service location for Cumbria.",

};

/**
 * Generates a Local Industry Spotlight paragraph for a given town.
 * Returns the specific paragraph if available, otherwise generates a
 * county-context-aware fallback paragraph.
 */
export function getTownSpotlight(
  townSlug: string,
  townName: string,
  countyName: string,
  countySlug: string,
  region: string
): string | null {
  // Return specific spotlight if available
  if (townSpotlight[townSlug]) {
    return townSpotlight[townSlug];
  }

  // No spotlight for this town — return null to use countyContext fallback
  return null;
}
