// Header mega-menu data — extracted into a separate module so it can be
// dynamically imported and kept out of the initial JS bundle.

export const serviceLinks = [
  { title: "Structural Steel Frames", href: "/services/structural-steel-frames", description: "Comprehensive shot blasting for building frames and trusses" },
  { title: "Steel Chimneys, Process Stacks & Flues", href: "/services/steel-chimney-surface-preparation", description: "Evidence-led surface preparation for fabricated chimneys, stacks, flues, and duct sections" },
  { title: "Steel Fabrications Blasting", href: "/steel-fabrications", description: "Before & after project photos — fabricated steel blasted to Sa 2.5" },
  { title: "Steel Container Blasting", href: "/services/steel-containers", description: "Specialist shot blasting for shipping containers and storage tanks" },
  { title: "Factory & Warehouse Cladding", href: "/services/factory-cladding", description: "Specialist cladding restoration removing plastisol and paint layers" },
  { title: "Fire Escapes & External Stair Towers", href: "/services/fire-escapes", description: "Specialist surface preparation for fire safety infrastructure" },
  { title: "Internal Steel Staircases, Balustrades & Handrails", href: "/services/staircases", description: "Precision shot blasting for architectural metalwork" },
  { title: "External Staircases Shot Blasting", href: "/external-staircases", description: "On-site shot blasting of external steel staircases to Sa 2.5 standard" },
  { title: "Bridge Steelwork (Girders, Crossmembers, Parapet Rails)", href: "/services/bridge-steelwork", description: "Comprehensive surface preparation for bridge infrastructure" },
  { title: "Fixed Ladders & Step-Over Platforms", href: "/services/ladders", description: "Comprehensive surface preparation for industrial access systems" },
  { title: "Warehouse Racking & Pallet Rack Frames", href: "/services/warehouse-racking", description: "Professional shot blasting for warehouse racking systems" },
  { title: "Process Pipework, Spools & Manifolds", href: "/services/pipework", description: "Precision cleaning of industrial pipework systems" },
  { title: "Telecom Masts & Lattice Towers", href: "/services/telecom-towers", description: "Specialist shot blasting for telecommunications infrastructure" },
  { title: "Floor Preparation & Shot Blasting", href: "/services/floor-preparation", description: "Professional floor surface preparation for commercial and industrial facilities" },
  { title: "Shot Blasting & Powder Coating", href: "/services/powder-coating", description: "End-to-end metal surface solutions combining shot blasting with powder coating" },
  { title: "Commercial Radiators", href: "/services/commercial-radiators", description: "Professional restoration for cast iron & steel radiators" },
  { title: "Commercial Vehicles", href: "/services/commercial-vehicles", description: "Heavy-duty restoration for farm & warehouse vehicles" },
  { title: "Steel Doors & Roller Shutters", href: "/services/steel-doors", description: "Professional restoration for industrial doors & security shutters" },
  { title: "Steel Sheeting", href: "/services/steel-sheeting", description: "Professional surface preparation for steel sheets and panels" },
  { title: "Steel Gates & Railings", href: "/services/steel-gates", description: "Precision restoration for commercial & industrial gates" },
  { title: "Plant & Machinery", href: "/services/plant-machinery", description: "On-site shot blasting for construction & agricultural equipment" },
  { title: "Intumescent Painting", href: "/services/intumescent-painting", description: "Fire-resistant coatings applied to perfectly prepared steel — R30 to R120" },
  { title: "Marine Shot Blasting", href: "/services/marine-shot-blasting", description: "Specialist shot blasting for vessels, lock gates, jetties, and port infrastructure" },
  { title: "Rust Removal", href: "/services/rust-removal", description: "Complete rust removal by shot blasting — faster and more thorough than grinding" },
  { title: "Mill Scale Removal", href: "/services/mill-scale-removal", description: "Complete mill scale removal for optimal coating adhesion on new fabrications" },
  { title: "Paint Stripping", href: "/services/paint-stripping", description: "Industrial paint stripping by shot blasting — all coats removed in one pass" },
  { title: "Coating Removal", href: "/services/coating-removal", description: "Specialist removal of epoxy, polyurethane, intumescent, and marine coatings" },
  { title: "Agricultural Shot Blasting", href: "/services/agricultural-shot-blasting", description: "Shot blasting for farm machinery, grain stores, and agricultural steelwork" },
  { title: "Car Park Paint & Line Marking Removal", href: "/services/car-park-paint-removal", description: "Mobile shot blasting to remove bay markings, thermoplastic road paint, and old coatings from tarmac and concrete" },
];

export const compactAreasLinks = [
  { region: "West Midlands", countyHref: "/counties/west-midlands", keyLocations: [{ title: "Birmingham", href: "/service-areas/birmingham" }, { title: "Wolverhampton", href: "/service-areas/wolverhampton" }, { title: "Coventry", href: "/service-areas/coventry" }], totalCount: 8 },
  { region: "Warwickshire", countyHref: "/counties/warwickshire", keyLocations: [{ title: "Leamington Spa", href: "/service-areas/leamington-spa" }, { title: "Rugby", href: "/service-areas/rugby" }], totalCount: 4 },
  { region: "Worcestershire", countyHref: "/counties/worcestershire", keyLocations: [{ title: "Worcester", href: "/service-areas/worcester" }, { title: "Kidderminster", href: "/service-areas/kidderminster" }], totalCount: 3 },
  { region: "Staffordshire", countyHref: "/counties/staffordshire", keyLocations: [{ title: "Stoke-on-Trent", href: "/service-areas/stoke" }, { title: "Stafford", href: "/service-areas/stafford" }], totalCount: 8 },
  { region: "Nottinghamshire", countyHref: "/counties/nottinghamshire", keyLocations: [{ title: "Nottingham", href: "/service-areas/nottingham" }, { title: "Mansfield", href: "/service-areas/mansfield" }], totalCount: 2 },
  { region: "Leicestershire", countyHref: "/counties/leicestershire", keyLocations: [{ title: "Leicester", href: "/service-areas/leicester" }, { title: "Loughborough", href: "/service-areas/loughborough" }], totalCount: 3 },
  { region: "Derbyshire", countyHref: "/counties/derbyshire", keyLocations: [{ title: "Derby", href: "/service-areas/derby" }, { title: "Chesterfield", href: "/service-areas/chesterfield" }], totalCount: 3 },
  { region: "Lincolnshire", countyHref: "/counties/lincolnshire", keyLocations: [{ title: "Lincoln", href: "/service-areas/lincoln" }, { title: "Grantham", href: "/service-areas/grantham" }], totalCount: 3 },
  { region: "Northamptonshire", countyHref: "/counties/northamptonshire", keyLocations: [{ title: "Northampton", href: "/service-areas/northampton" }, { title: "Kettering", href: "/service-areas/kettering" }], totalCount: 4 },
  { region: "South Yorkshire", countyHref: "/counties/south-yorkshire", keyLocations: [{ title: "Sheffield", href: "/service-areas/sheffield" }, { title: "Doncaster", href: "/service-areas/doncaster" }], totalCount: 4 },
  { region: "West Yorkshire", countyHref: "/counties/west-yorkshire", keyLocations: [{ title: "Leeds", href: "/service-areas/leeds" }, { title: "Bradford", href: "/service-areas/bradford" }], totalCount: 5 },
  { region: "North Yorkshire", countyHref: "/counties/north-yorkshire", keyLocations: [{ title: "York", href: "/service-areas/york" }, { title: "Harrogate", href: "/service-areas/harrogate" }], totalCount: 3 },
  { region: "Tyne & Wear", countyHref: "/counties/tyne-and-wear", keyLocations: [{ title: "Newcastle", href: "/service-areas/newcastle-upon-tyne" }, { title: "Sunderland", href: "/service-areas/sunderland" }], totalCount: 6 },
  { region: "County Durham", countyHref: "/counties/durham", keyLocations: [{ title: "Durham City", href: "/service-areas/durham" }, { title: "Darlington", href: "/service-areas/darlington" }], totalCount: 5 },
  { region: "Northumberland", countyHref: "/counties/northumberland", keyLocations: [{ title: "Morpeth", href: "/service-areas/morpeth" }, { title: "Hexham", href: "/service-areas/hexham" }], totalCount: 4 },
  { region: "Cumbria", countyHref: "/counties/cumbria", keyLocations: [{ title: "Carlisle", href: "/service-areas/carlisle" }, { title: "Barrow-in-Furness", href: "/service-areas/barrow-in-furness" }], totalCount: 5 },
  { region: "Lancashire", countyHref: "/counties/lancashire", keyLocations: [{ title: "Preston", href: "/service-areas/preston" }, { title: "Blackburn", href: "/service-areas/blackburn" }], totalCount: 8 },
  { region: "Greater Manchester", countyHref: "/service-areas#greater-manchester", keyLocations: [{ title: "Manchester", href: "/service-areas/manchester" }, { title: "Bolton", href: "/service-areas/bolton" }], totalCount: 6 },
  { region: "Merseyside", countyHref: "/service-areas#merseyside", keyLocations: [{ title: "Liverpool", href: "/service-areas/liverpool" }, { title: "Birkenhead", href: "/service-areas/birkenhead" }], totalCount: 2 },
  { region: "Cheshire", countyHref: "/counties/cheshire", keyLocations: [{ title: "Chester", href: "/service-areas/chester" }, { title: "Crewe", href: "/service-areas/crewe" }], totalCount: 5 },
  { region: "Norfolk", countyHref: "/counties/norfolk", keyLocations: [{ title: "Norwich", href: "/service-areas/norwich" }, { title: "King's Lynn", href: "/service-areas/kings-lynn" }], totalCount: 5 },
  { region: "Suffolk", countyHref: "/counties/suffolk", keyLocations: [{ title: "Ipswich", href: "/service-areas/ipswich" }, { title: "Bury St Edmunds", href: "/service-areas/bury-st-edmunds" }], totalCount: 3 },
  { region: "Cambridgeshire", countyHref: "/counties/cambridgeshire", keyLocations: [{ title: "Cambridge", href: "/service-areas/cambridge" }, { title: "Peterborough", href: "/service-areas/peterborough" }], totalCount: 2 },
  { region: "Essex", countyHref: "/counties/essex", keyLocations: [{ title: "Colchester", href: "/service-areas/colchester" }, { title: "Chelmsford", href: "/service-areas/chelmsford" }], totalCount: 4 },
  { region: "Hertfordshire", countyHref: "/counties/hertfordshire", keyLocations: [{ title: "St Albans", href: "/service-areas/st-albans" }, { title: "Watford", href: "/service-areas/watford" }], totalCount: 4 },
  { region: "Bedfordshire", countyHref: "/counties/bedfordshire", keyLocations: [{ title: "Bedford", href: "/service-areas/bedford" }, { title: "Luton", href: "/service-areas/luton" }], totalCount: 3 },
  { region: "Bristol & Bath", countyHref: "/service-areas#bristol-bath", keyLocations: [{ title: "Bristol", href: "/service-areas/bristol" }, { title: "Bath", href: "/service-areas/bath" }], totalCount: 3 },
  { region: "Gloucestershire", countyHref: "/counties/gloucestershire", keyLocations: [{ title: "Gloucester", href: "/service-areas/gloucester" }, { title: "Cheltenham", href: "/service-areas/cheltenham" }], totalCount: 2 },
  { region: "Wiltshire", countyHref: "/counties/wiltshire", keyLocations: [{ title: "Swindon", href: "/service-areas/swindon" }, { title: "Salisbury", href: "/service-areas/salisbury" }], totalCount: 2 },
  { region: "Somerset", countyHref: "/counties/somerset", keyLocations: [{ title: "Taunton", href: "/service-areas/taunton" }, { title: "Weston-super-Mare", href: "/service-areas/weston-super-mare" }], totalCount: 2 },
  { region: "Oxfordshire", countyHref: "/service-areas#oxfordshire", keyLocations: [{ title: "Oxford", href: "/service-areas/oxford" }, { title: "Banbury", href: "/service-areas/banbury" }], totalCount: 2 },
  { region: "Berkshire", countyHref: "/counties/berkshire", keyLocations: [{ title: "Reading", href: "/service-areas/reading" }, { title: "Slough", href: "/service-areas/slough" }], totalCount: 2 },
  { region: "Buckinghamshire", countyHref: "/counties/buckinghamshire", keyLocations: [{ title: "Milton Keynes", href: "/service-areas/milton-keynes" }, { title: "Aylesbury", href: "/service-areas/aylesbury" }], totalCount: 3 },
  { region: "Surrey", countyHref: "/service-areas#surrey", keyLocations: [{ title: "Guildford", href: "/service-areas/guildford" }], totalCount: 1 },
  { region: "Hampshire", countyHref: "/counties/hampshire", keyLocations: [{ title: "Portsmouth", href: "/service-areas/portsmouth" }, { title: "Southampton", href: "/service-areas/southampton" }], totalCount: 3 },
  { region: "Shropshire", countyHref: "/counties/shropshire", keyLocations: [{ title: "Shrewsbury", href: "/service-areas/shrewsbury" }, { title: "Telford", href: "/service-areas/telford" }], totalCount: 2 },
  { region: "Herefordshire", countyHref: "/counties/herefordshire", keyLocations: [{ title: "Hereford", href: "/service-areas/hereford" }], totalCount: 1 },
  { region: "Wales", countyHref: "/counties/east-wales", keyLocations: [{ title: "Cardiff", href: "/service-areas/cardiff" }, { title: "Wrexham", href: "/service-areas/wrexham" }], totalCount: 3 },
];

export const fullAreasLinks = [
  { region: "West Midlands", locations: [{ title: "Birmingham", href: "/service-areas/birmingham" }, { title: "Wolverhampton", href: "/service-areas/wolverhampton" }, { title: "Coventry", href: "/service-areas/coventry" }, { title: "Dudley", href: "/service-areas/dudley" }, { title: "Solihull", href: "/service-areas/solihull" }, { title: "Sutton Coldfield", href: "/service-areas/sutton-coldfield" }, { title: "Walsall", href: "/service-areas/walsall" }, { title: "Nuneaton", href: "/service-areas/nuneaton" }] },
  { region: "Warwickshire", locations: [{ title: "Leamington Spa", href: "/service-areas/leamington-spa" }, { title: "Rugby", href: "/service-areas/rugby" }, { title: "Stratford Upon Avon", href: "/service-areas/stratford-upon-avon" }, { title: "Nuneaton", href: "/service-areas/nuneaton" }] },
  { region: "Worcestershire", locations: [{ title: "Worcester", href: "/service-areas/worcester" }, { title: "Kidderminster", href: "/service-areas/kidderminster" }, { title: "Redditch", href: "/service-areas/redditch" }] },
  { region: "Staffordshire", locations: [{ title: "Stoke-on-Trent", href: "/service-areas/stoke" }, { title: "Stafford", href: "/service-areas/stafford" }, { title: "Burton upon Trent", href: "/service-areas/burton-on-trent" }, { title: "Cannock", href: "/service-areas/cannock" }, { title: "Cannock Chase", href: "/service-areas/cannock-chase" }, { title: "Lichfield", href: "/service-areas/lichfield" }, { title: "Tamworth", href: "/service-areas/tamworth" }, { title: "Newcastle-under-Lyme", href: "/service-areas/newcastle-under-lyme" }] },
  { region: "Nottinghamshire", locations: [{ title: "Nottingham", href: "/service-areas/nottingham" }, { title: "Mansfield", href: "/service-areas/mansfield" }] },
  { region: "Leicestershire", locations: [{ title: "Leicester", href: "/service-areas/leicester" }, { title: "Loughborough", href: "/service-areas/loughborough" }, { title: "Coalville", href: "/service-areas/coalville" }] },
  { region: "Derbyshire", locations: [{ title: "Derby", href: "/service-areas/derby" }, { title: "Chesterfield", href: "/service-areas/chesterfield" }, { title: "Dronfield", href: "/service-areas/dronfield" }] },
  { region: "Lincolnshire", locations: [{ title: "Lincoln", href: "/service-areas/lincoln" }, { title: "Grantham", href: "/service-areas/grantham" }, { title: "Scunthorpe", href: "/service-areas/scunthorpe" }] },
  { region: "Northamptonshire", locations: [{ title: "Northampton", href: "/service-areas/northampton" }, { title: "Kettering", href: "/service-areas/kettering" }, { title: "Corby", href: "/service-areas/corby" }, { title: "Wellingborough", href: "/service-areas/wellingborough" }] },
  { region: "South Yorkshire", locations: [{ title: "Sheffield", href: "/service-areas/sheffield" }, { title: "Barnsley", href: "/service-areas/barnsley" }, { title: "Doncaster", href: "/service-areas/doncaster" }, { title: "Rotherham", href: "/service-areas/rotherham" }] },
  { region: "West Yorkshire", locations: [{ title: "Leeds", href: "/service-areas/leeds" }, { title: "Bradford", href: "/service-areas/bradford" }, { title: "Huddersfield", href: "/service-areas/huddersfield" }, { title: "Halifax", href: "/service-areas/halifax" }, { title: "Wakefield", href: "/service-areas/wakefield" }, { title: "Dewsbury", href: "/service-areas/dewsbury" }] },
  { region: "North Yorkshire", locations: [{ title: "York", href: "/service-areas/york" }, { title: "Harrogate", href: "/service-areas/harrogate" }, { title: "Scarborough", href: "/service-areas/scarborough" }, { title: "Northallerton", href: "/service-areas/northallerton" }] },
  { region: "Tyne & Wear", locations: [{ title: "Newcastle upon Tyne", href: "/service-areas/newcastle-upon-tyne" }, { title: "Sunderland", href: "/service-areas/sunderland" }, { title: "Gateshead", href: "/service-areas/gateshead" }, { title: "South Shields", href: "/service-areas/south-shields" }, { title: "Wallsend", href: "/service-areas/wallsend" }, { title: "Jarrow", href: "/service-areas/jarrow" }] },
  { region: "County Durham", locations: [{ title: "Durham City", href: "/service-areas/durham" }, { title: "Darlington", href: "/service-areas/darlington" }, { title: "Hartlepool", href: "/service-areas/hartlepool" }, { title: "Newton Aycliffe", href: "/service-areas/newton-aycliffe" }, { title: "Peterlee", href: "/service-areas/peterlee" }] },
  { region: "Northumberland", locations: [{ title: "Morpeth", href: "/service-areas/morpeth" }, { title: "Hexham", href: "/service-areas/hexham" }, { title: "Alnwick", href: "/service-areas/alnwick" }, { title: "Blyth", href: "/service-areas/blyth" }] },
  { region: "Cumbria", locations: [{ title: "Carlisle", href: "/service-areas/carlisle" }, { title: "Barrow-in-Furness", href: "/service-areas/barrow-in-furness" }, { title: "Kendal", href: "/service-areas/kendal" }, { title: "Workington", href: "/service-areas/workington" }, { title: "Whitehaven", href: "/service-areas/whitehaven" }] },
  { region: "Lancashire", locations: [{ title: "Preston", href: "/service-areas/preston" }, { title: "Blackburn", href: "/service-areas/blackburn" }, { title: "Burnley", href: "/service-areas/burnley" }, { title: "Lancaster", href: "/service-areas/lancaster" }, { title: "Chorley", href: "/service-areas/chorley" }, { title: "Blackpool", href: "/service-areas/blackpool" }, { title: "Accrington", href: "/service-areas/accrington" }, { title: "Leyland", href: "/service-areas/leyland" }] },
  { region: "Greater Manchester", locations: [{ title: "Manchester", href: "/service-areas/manchester" }, { title: "Bolton", href: "/service-areas/bolton" }, { title: "Oldham", href: "/service-areas/oldham" }, { title: "Rochdale", href: "/service-areas/rochdale" }, { title: "Salford", href: "/service-areas/salford" }, { title: "Stockport", href: "/service-areas/stockport" }] },
  { region: "Merseyside", locations: [{ title: "Liverpool", href: "/service-areas/liverpool" }, { title: "Birkenhead", href: "/service-areas/birkenhead" }] },
  { region: "Cheshire", locations: [{ title: "Chester", href: "/service-areas/chester" }, { title: "Warrington", href: "/service-areas/warrington" }, { title: "Runcorn", href: "/service-areas/runcorn" }, { title: "Crewe", href: "/service-areas/crewe" }, { title: "Macclesfield", href: "/service-areas/macclesfield" }] },
  { region: "Norfolk", locations: [{ title: "Norwich", href: "/service-areas/norwich" }, { title: "King's Lynn", href: "/service-areas/kings-lynn" }, { title: "Great Yarmouth", href: "/service-areas/great-yarmouth" }, { title: "Thetford", href: "/service-areas/thetford" }, { title: "Lowestoft", href: "/service-areas/lowestoft" }] },
  { region: "Suffolk", locations: [{ title: "Ipswich", href: "/service-areas/ipswich" }, { title: "Bury St Edmunds", href: "/service-areas/bury-st-edmunds" }, { title: "Lowestoft", href: "/service-areas/lowestoft" }] },
  { region: "Cambridgeshire", locations: [{ title: "Cambridge", href: "/service-areas/cambridge" }, { title: "Peterborough", href: "/service-areas/peterborough" }] },
  { region: "Essex", locations: [{ title: "Colchester", href: "/service-areas/colchester" }, { title: "Chelmsford", href: "/service-areas/chelmsford" }, { title: "Basildon", href: "/service-areas/basildon" }, { title: "Southend-on-Sea", href: "/service-areas/southend-on-sea" }] },
  { region: "Hertfordshire", locations: [{ title: "St Albans", href: "/service-areas/st-albans" }, { title: "Watford", href: "/service-areas/watford" }, { title: "Stevenage", href: "/service-areas/stevenage" }, { title: "Hemel Hempstead", href: "/service-areas/hemel-hempstead" }, { title: "Welwyn Garden City", href: "/service-areas/welwyn-garden-city" }] },
  { region: "Bedfordshire", locations: [{ title: "Bedford", href: "/service-areas/bedford" }, { title: "Luton", href: "/service-areas/luton" }, { title: "Leighton Buzzard", href: "/service-areas/leighton-buzzard" }] },
  { region: "Bristol & Bath", locations: [{ title: "Bristol", href: "/service-areas/bristol" }, { title: "Bath", href: "/service-areas/bath" }, { title: "Kingswood", href: "/service-areas/kingswood" }] },
  { region: "Gloucestershire", locations: [{ title: "Gloucester", href: "/service-areas/gloucester" }, { title: "Cheltenham", href: "/service-areas/cheltenham" }] },
  { region: "Wiltshire", locations: [{ title: "Swindon", href: "/service-areas/swindon" }, { title: "Salisbury", href: "/service-areas/salisbury" }] },
  { region: "Somerset", locations: [{ title: "Taunton", href: "/service-areas/taunton" }, { title: "Weston-super-Mare", href: "/service-areas/weston-super-mare" }] },
  { region: "Oxfordshire", locations: [{ title: "Oxford", href: "/service-areas/oxford" }, { title: "Banbury", href: "/service-areas/banbury" }] },
  { region: "Berkshire", locations: [{ title: "Reading", href: "/service-areas/reading" }, { title: "Slough", href: "/service-areas/slough" }] },
  { region: "Buckinghamshire", locations: [{ title: "Milton Keynes", href: "/service-areas/milton-keynes" }, { title: "Aylesbury", href: "/service-areas/aylesbury" }, { title: "High Wycombe", href: "/service-areas/high-wycombe" }] },
  { region: "Surrey", locations: [{ title: "Guildford", href: "/service-areas/guildford" }] },
  { region: "Hampshire", locations: [{ title: "Portsmouth", href: "/service-areas/portsmouth" }, { title: "Southampton", href: "/service-areas/southampton" }, { title: "Basingstoke", href: "/service-areas/basingstoke" }] },
  { region: "Shropshire", locations: [{ title: "Shrewsbury", href: "/service-areas/shrewsbury" }, { title: "Telford", href: "/service-areas/telford" }] },
  { region: "Herefordshire", locations: [{ title: "Hereford", href: "/service-areas/hereford" }] },
  { region: "Wales", locations: [{ title: "Cardiff", href: "/service-areas/cardiff" }, { title: "Wrexham", href: "/service-areas/wrexham" }, { title: "Newport", href: "/service-areas/newport" }] },
];
